# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email ""
      git config --global user.name ""

- task: CmdLine@2
  inputs:
    script: 'git branch -r | grep -v ''\->'' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done'
    failOnStderr: true

- task: CmdLine@2
  inputs:
    script: 'git pull https://$(VSTSToken)@dev.azure.com/hyneskhater/ADM.Portfolio/_git/HK.oqtane.framework.git -u --all'

- task: CmdLine@2
  inputs:
    script: 'git push https://$(VSTSToken)@dev.azure.com/hyneskhater/ADM.Portfolio/_git/HK.oqtane.framework.git -u --all'
